### ISSUE TITLE
Dark Blue does not work

### ISSUE THREAD

**Issue by DJKnaeckebrot** [Morten010/nextui-themes#1]
When selecting the dark blue theme on the webpage it returns the color values for posthog theme.

![image](https://github.com/Morten010/nextui-themes/assets/46864390/8c853fc0-eaa6-4bc0-af43-c0421a541f1a)

Keep up the great work! :)

**Comment by Morten010** [comment]
they just look very similar in main colors, otherwise the link would be orange like on posthog and thanks.
